version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - sqlite-db:/usr/src/app/prisma   # Mapeia o diretório onde o arquivo do banco de dados SQLite está localizado
    command: npm start

volumes:
  sqlite-db:
